src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private int $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\Email(groups={"registration"})
     */
    private ?string $email;

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     * @Assert\NotBlank(groups={"registration"})
     * @Assert\Length(min=7, groups={"registration"})
     */
    private string $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(min=3, groups={"identity"})
     */
    private ?string $firstName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(min=3, groups={"identity"})
     */
    private ?string $lastName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(min=3, groups={"identity"})
     */
    private string $userName;

    /**
     * @ORM\OneToOne(targetEntity=Image::class, cascade={"persist", "remove"})
     * @Assert\Image(
     *     minWidth = 800,
     *     maxWidth = 1600,
     *     minHeight = 800,
     *     maxHeight = 1600
     * , groups={"image"})
     */
    private ?Image $profilePic;

    /**
     * @ORM\Column(type="json")
     */
    private array $roles = [];

    /**
     * @ORM\Column(type="boolean")
     */
    private bool $isVerified = false;

    /**
    * @ORM\OneToMany(targetEntity=Trick::class, mappedBy="author", orphanRemoval=true)
    */
    private Collection $tricks;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="author", orphanRemoval=true)
     */
    private Collection $comments;

    public function __construct()
    {
        $this->tricks = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    public function setUserName(string $userName): self
    {
        $this->userName = $userName;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(?string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(?string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getIsVerified(): ?bool
    {
        return $this->isVerified;
    }

    /**
     * @return Collection|Trick[]
     */
    public function getTricks(): Collection
    {
        return $this->tricks;
    }

    public function addTrick(Trick $trick): self
    {
        if (!$this->tricks->contains($trick)) {
            $this->tricks[] = $trick;
            $trick->setAuthor($this);
        }

        return $this;
    }

    public function removeTrick(Trick $trick): self
    {
        if ($this->tricks->removeElement($trick)) {
            // set the owning side to null (unless already changed)
            if ($trick->getAuthor() === $this) {
                $trick->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAuthor($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAuthor() === $this) {
                $comment->setAuthor(null);
            }
        }

        return $this;
    }

    public function getProfilePic(): ?Image
    {
        return $this->profilePic;
    }

    public function setProfilePic(?Image $profilePic): self
    {
        $this->profilePic = $profilePic;

        return $this;
    }
}

templates/blocs_home/_header.html.twig
<!-- Masthead-->
<header class="masthead bg-header text-white text-center">
{#    <div class="container ">#}
        <!-- Masthead Heading-->
        <h1 class="masthead-heading text-uppercase mb-0 mt-sm-0 pt-sm-0">SnowTricks</h1>
        <!-- Icon Divider-->
        <div class="divider-custom divider-light">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i aria-hidden="true" class="fas fa-star" role="img"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Masthead Avatar Image-->
        <img class="masthead-avatar " src="{{ asset('build/img/snowboard-and-mountain.jpg') }}" alt="" />
        <!-- Masthead Subheading-->
        <p class="masthead-subheading font-weight-light my-sm-5 ">Take The Ride Now</p>
        <a href="#portfolio" class="bg-dark mt-2 py-2 px-3" aria-label="Show Tricks List section"><i aria-hidden="true" class="fas fa-angle-double-down fa-lg"></i></a>
{#    </div>#}
</header>

templates/blocs_home/_nav.html.twig
<nav class="navbar  navbar-expand-lg text-uppercase fixed-top align-items-center" id="mainNav" >
    <a class="navbar-brand js-scroll-trigger" href="{{path('index')}}">SnowTricks</a>
    <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars" aria-hidden="true"></i>
        <span class="sr-only">Menu</span>
    </button>
    <div class="collapse navbar-collapse  " id="navbarResponsive">
        <ul class="navbar-nav ml-auto align-items-lg-center mt-0">
            <li class="nav-item mx-0 mx-lg-1">
                <a class="nav-link py-lg-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{{ path('index') }}">Home</a>
            </li>
            <li class="nav-item mx-0 mx-lg-1">
                <a class="nav-link py-lg-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{{ path('trick_index') }}">Tricks</a>
            </li>
            {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %}
                <li class="nav-item mx-0 mx-lg-1">
                    <div class="dropdown">
                        <button type="button" class="btn bg-transparent text-white-50 dropdown-toggle pl-0 " data-toggle="dropdown">
                            Welcome {{ app.user.firstName ? app.user.firstName : app.user.username}}
                        </button>
                        <div class="dropdown-menu w-100 text-center">
                            <a class="dropdown-item" href="{{ path('user_account',{'id':app.user.id}) }}">My Account</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{{ path('app_logout') }}">Logout</a>
                        </div>
                    </div>
                </li>
            {% else %}
                <li class="nav-item mx-0 mx-lg-1">
                    <a class="nav-link py-lg-3  px-0 px-lg-3 rounded js-scroll-trigger js-scroll" href="{{ path('app_login') }}">Sign In</a>
                </li>
                <li class="nav-item mx-0 mx-lg-1">
                    <a class="nav-link py-lg-3  px-0 px-lg-3 rounded js-scroll-trigger js-scroll" href="{{ path('app_register') }}">Sign Up</a>
                </li>
            {% endif %}
           {% include '_international.html.twig' %}
        </ul>
    </div>
</nav>

templates/blocs_home/_portfolio.html.twig
{% set target = "#portfolio" %}
<!-- Portfolio Section-->
<section class="page-section portfolio" id="portfolio">
    <div class="container">
        <!-- Portfolio Section Heading-->
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Tricks</h2>
        <!-- Icon Divider-->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i aria-hidden="true" class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Portfolio Grid Items-->
        <div class="trick-box text-center">
            {{include ('trick/_list.html.twig',{'target':target})}}
        </div>
    </div>
</section>